site_name: Records2 Documentation
site_url: https://records2-docs.example.com
repo_url: https://github.com/nexios-labs/records2
repo_name: nexios-labs/records2
nav:
  - Home: index.md
  - User Guide:
      - Getting Started: user-guide/getting-started.md
      - Advanced Usage: user-guide/advanced.md
      - API Reference: api/index.md
      - Examples: examples/index.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - About: about.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: indigo
      accent: pink
    - scheme: slate
      primary: indigo
      accent: pink
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.tooltips
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.highlight
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - pip install .
          options:
            show_root_heading: true
            show_root_full_path: false
            show_object_full_path: false
            show_signature_annotations: true
            show_source: true
            show_bases: true
            show_inheritance_diagram: true
            show_category_heading: true
            show_submodules: true
            show_module_summary: true
            show_if_no_docstring: true
            show_docstring_examples: true
            show_docstring_section_headers: true
            show_docstring_code_blocks: true
            show_docstring_parameters: true
            show_docstring_returns: true
            show_docstring_raises: true
            show_docstring_attributes: true
            show_docstring_methods: true
            show_docstring_classes: true
            show_docstring_functions: true
            show_docstring_properties: true
            show_docstring_exceptions: true
            show_docstring_other: true
            show_docstring_notes: true
            show_docstring_references: true
            show_docstring_todo: true
            show_docstring_deprecated: true
            show_docstring_seealso: true
            show_docstring_warnings: true
            show_docstring_versionadded: true
            show_docstring_versionchanged: true
            show_docstring_abstract: true
            show_docstring_private: true
            show_docstring_special: true
            show_docstring_summary: true
            show_docstring_description: true
            show_docstring_examples: true
            show_docstring_parameters: true
            show_docstring_returns: true
            show_docstring_raises: true
            show_docstring_attributes: true
            show_docstring_methods: true
            show_docstring_classes: true
            show_docstring_functions: true
            show_docstring_properties: true
            show_docstring_exceptions: true
            show_docstring_other: true
            show_docstring_notes: true
            show_docstring_examples: true
            show_docstring_references: true
            show_docstring_todo: true
            show_docstring_deprecated: true
            show_docstring_seealso: true
            show_docstring_warnings: true
            show_docstring_versionadded: true
            show_docstring_versionchanged: true
            show_docstring_abstract: true
            show_docstring_private: true
            show_docstring_special: true
            show_docstring_summary: true
            show_docstring_description: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nexios-labs/records2
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nexioslabs
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/nexios-labs
